intel/SGXDataCenterAttestationPrimitives

- driver/License.txt
Incorrect license file was in use.
All source files can be released under dual license GPL/BSD.
> Correcting license file

- README.md
> Update driver license in README.md

- README.md
- driver/win/Driver Install Guide.txt
- driver/win/README.md
Add a README file for Windows driver.
Signed-off-by: Zhang Lili Z <lili.z.zhang@intel.com>
> Add a README file and remove one unnecessary install doc for Windows driver

- QuoteGeneration/README.md
- QuoteGeneration/installer/win/Dcap/dcap_generate.bat
Signed-off-by: Zhang Lili Z <lili.z.zhang@intel.com>
> Refine installer and README

- driver/linux/sgx_encl.c
- driver/linux/sgx_main.c
- driver/linux/sgx_util.c
> Merging updates from OOT driver

- driver/linux/le/enclave/ThirdPartyLicenses.txt
Signed-off-by: Zhang Lili Z <lili.z.zhang@intel.com>
> Add ThirdPartyLicenses.txt

- driver/linux/dkms.conf
- driver/linux/sgx_main.c
> Updated the driver version

- QuoteGeneration/pcs/README.md
- QuoteGeneration/qpl/README.md
- QuoteGeneration/qpl/qpl_api.txt
updated below files:
QuoteGeneration/pcs/README.md
QuoteGeneration/qpl/README.md
QuoteGeneration/qpl/qpl_api.txt
> Update readme files

- driver/linux/include/asm/sgx_arch.h
- driver/win/WinLeProxyUMDF/FLC_Enclave/sgx_arch.h
> Fixed SECS.configid offset

- driver/linux/dkms.conf
- driver/linux/le/enclave/sgxsign.c
- driver/linux/sgx_version.h
Reverts intel/SGXDataCenterAttestationPrimitives#30
> Revert "Fixed date format in sigstruct + version update"

- driver/linux/dkms.conf
- driver/linux/le/enclave/sgxsign.c
- driver/linux/sgx_version.h
> Fixed PLE signing tool bug in Q1,Q2 calculation.

- driver/linux/dkms.conf
- driver/linux/include/asm/sgx_arch.h
- driver/linux/sgx_page_cache.c
- driver/linux/sgx_version.h
- driver/linux/sgx_vma.c
> Removed wrong check on EDBGWR

- QuoteGeneration/common/src/se_map.c
> Fix memory leak issue in se_map.c

- driver/linux/dkms.conf
- driver/linux/sgx_encl.c
- driver/linux/sgx_main.c
- driver/linux/sgx_version.h
> Fixed potential overflow on SSA frame size calculation.

- driver/linux/README.md
- driver/linux/encl.c
Reverts intel/SGXDataCenterAttestationPrimitives#72
> Revert "Linux pr"

- driver/linux/README.md
Reverts intel/SGXDataCenterAttestationPrimitives#70
> Revert "Linux Driver: add instructions to enable and disable autoload"

- driver/linux/README.md
> Update change log for V1.32

- driver/linux/README.md
- driver/linux/dkms.conf
- driver/linux/version.h
> Update version to 1.33

- driver/linux/encl.c
> Linux Driver: fix a build error for Ubuntu 20.04

- driver/linux/README.md
- driver/linux/dkms.conf
- driver/linux/encl.c
- driver/linux/version.h
> Linux Driver: Fix build for RHEL 8.2

- driver/linux/README.md
- driver/linux/dkms.conf
- driver/linux/driver.c
- driver/linux/encl.c
- driver/linux/encl.h
- driver/linux/ioctl.c
- driver/linux/main.c
- driver/linux/sgx.h
- driver/linux/version.h
> Linux Driver: Sync with upstream patches v36

- driver/linux/README.md
Add CentOS support
Change minimal kernel version for Ubuntu to 4.15
Remove instructions for add/remove entries in /etc/modules
Add command to remake initrd for RHEL and CentOS for uninstall.
> Linux Driver: update README

- driver/linux/main.c
- driver/linux/sgx.h
> Linux Driver: improve error messages

- driver/linux/README.md
> Linux Driver: update README for compatibility matrix

- driver/linux/Makefile
> Linux Driver: hardening compiler options

- QuoteGeneration/README.md
- QuoteVerification/README.md
- SampleCode/QuoteGenerationSample/README.md
- SampleCode/QuoteVerificationSample/README.md
Signed-off-by: Zhang Lili <lili.z.zhang@intel.com>
> Remove Ubuntu 16.04 from README

- QuoteGeneration/installer/linux/rpm/tdx-qgs/tdx-qgs.spec
- tools/PCKRetrievalTool/installer/rpm/sgx-pck-id-retrieval-tool/sgx-pck-id-retrieval-tool.spec
- tools/SGXPlatformRegistration/package/installer/rpm/sgx-ra-service/sgx-ra-service.spec
Fix same issues mentioned in https://github.com/intel/linux-sgx/pull/858
> Update several deb package to use posttrans scriptlet

- QuoteGeneration/pccs/services/platformCollateralService.js
Signed-off-by: lingyuji <lingyu.jiang@intel.com>
> Missed PLATFORM_COLLATERAL_SCHEMA_V3

- tools/PccsAdminTool/lib/intelsgx/pcs.py
Signed-off-by: lingyuji <lingyu.jiang@intel.com>
> Fix PCCS Admin Tool for E3 platforms

- QuoteGeneration/README.md
The current list of hardware requirements is outdated.
> Update hardware requirements for Quote Generation Library

- QuoteGeneration/quote_wrapper/common/inc/sgx_ql_lib_common.h
Signed-off-by: Zijie Wu <noojeff@gmail.com>
> Remove trailing whitespaces in sgx_ql_lib_common.h

- QuoteVerification/dcap_quoteverify/inc/sgx_dcap_quoteverify.h
> Fix typo in sgx_dcap_quoteverify.h

- QuoteGeneration/qcnl/inc/qcnl_util.h
- QuoteVerification/QVL/Src/AttestationCommons/include/OpensslHelpers/Bytes.h
- QuoteVerification/QVL/Src/AttestationParsers/include/SgxEcdsaAttestation/AttestationParsers.h
- tools/PCKCertSelection/PCKCertSelectionLib/Makefile
- tools/PCKCertSelection/PCKCertSelectionLib/Makefile.static_lib
Some changes are still workaround
> Update to pass build on Ubuntu 23.10

- QuoteGeneration/buildenv.mk
- QuoteGeneration/pce_wrapper/linux/Makefile
- QuoteGeneration/qcnl/linux/Makefile
- QuoteGeneration/qpl/linux/Makefile
- QuoteGeneration/quote_wrapper/ql/linux/Makefile
- QuoteGeneration/quote_wrapper/quote/enclave/linux/Makefile
- QuoteGeneration/quote_wrapper/quote/id_enclave/linux/Makefile
- QuoteGeneration/quote_wrapper/quote/linux/Makefile
- QuoteGeneration/quote_wrapper/tdx_quote/enclave/linux/Makefile
- QuoteGeneration/quote_wrapper/tdx_quote/linux/Makefile
- QuoteVerification/QvE/Makefile
- QuoteVerification/dcap_quoteverify/linux/Makefile
- tools/PCKCertSelection/PCKCertSelectionLib/Makefile
As Canonical proposed, to create the soft link at build time
> Implement the proposed solution of library versioning

- README.md
Third-party code and license file moved to a submodule.
> Fix broken hyperlink in README

- QuoteGeneration/quote_wrapper/servtd_attest/inc/servtd_com.h
- QuoteVerification/QvE/Enclave/qve.cpp
Add tdx identity for migration, 
Return extra `attributes/attribute_mask`, `misc_select/misc_select_mask` after passing quote check
> Add Misc Selection Mask and Attributes Mask for Migration TD

- .github/codeql/codeql-config.yml
- .github/workflows/codeql.yml
Trigger C/C++  CodeQL Analysis when push, pull request and once per week on main branch.
Exclude code from submodules and third party.
> Create codeql.yml to enable CodeQL Analysis

- .github/workflows/c-cpp.yml
- .github/workflows/codeql.yml
Added `apt-get update` to actions according to [GitHub Actions Docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners).
> Fix GitHub Actions
