QuoteGeneration/common/inc/internal/elfheader/elf_common.h
QuoteGeneration/common/inc/internal/elfheader/elfstructs.h

This is necessary so that these headers can be compiled independently of their uses. Currently, the project's Makefiles rely on the inclusion of stdint.h in locations where elf_common.h and elfstructs.h are used, but this pattern will not necessary work in other build systems.

Add missing include for <stdint.h>

---

driver/linux/sgx_util.c

Assign CRYPTO_TFM_REQ_MAY_SLEEP to crt_flags defined in struct
crypto_tfm, instead of flags in struct shash_desc since
struct shash_desc u32 flags have been redefined in struct crypto_tfm
starting from kernel v5.2:
https://elixir.bootlin.com/linux/v5.2.2/source/include/linux/crypto.h#L751
https://elixir.bootlin.com/linux/v5.1.19/source/include/crypto/hash.h#L147
Signed-off-by: Iyer, Naveen <naveen.iyer@intel.com>

sgx_util: flags redefined as crt_flags in >= v5.2

---

QuoteGeneration/qcnl/sgx_default_qcnl_wrapper.cpp

HTTP headers are supposed to be case-insensitive. The client code is looking for lower-case headers, so the HTTP headers received from the server (which might be mixed case) need to be converted to lower case.

Convert incoming HTTP header names to lower case.

---

driver/linux/Makefile
driver/linux/README.md
driver/linux/dkms.conf
driver/linux/sgx_encl.c
driver/linux/sgx_version.h

- Fail driver build when kernel is supporting SGX
- Fail with EACCES when trying to launch an enclave with provision bit set without proper permission
- Cleanup the readme file to reflect the PLE removal

Minor fixes for DCAP driver

---

QuoteVerification/QVL/Src/AttestationLibrary/src/QuoteVerification/QuoteConstants.h

According to Intel_SGX_ECDSA_QuoteGenReference_DCAP_API_Linux_1.2.pdf:
the "Attestation Key Type" constants are:
- 2 (ECDSA-256-with-P-256 curve)
- 3 (ECDSA-384-with-P-384 curve) (Note: currently not supported)
(Note: 0 and 1 are reserved, EPID is moved to
version 3 quotes.)

Fix incorrect key type constants

---

driver/linux/README.md

updated README for linux driver. Driver based on v26 kernel patch defines
sgx devices as misc devices. ACPI ID based hotplug is no longer supported.

Linux Driver: add instructions to enable and disable autoload

---

QuoteVerification/QvE/Include/qve_header.h

* rename SGX_QL_MK_ERROR to SGX_QL_QV_MK_ERROR
the SGX_QL_MK_ERROR in `qve_header.h` has the same name as it in `sgx_ql_lib_common.h`, so it will never be defined as (0x0000A000|(x)).
duplicated codes:
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/c2bab2b3ccd80e45dbd5b7bf61d28f92a96d776e/QuoteVerification/QvE/Include/qve_header.h#L83
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/c2bab2b3ccd80e45dbd5b7bf61d28f92a96d776e/QuoteGeneration/quote_wrapper/common/inc/sgx_ql_lib_common.h#L44
Signed-off-by: Guan Jixing <guanjixing@baidu.com>

Fix(qve_header.h): typo of SGX_QL_MK_ERROR

---

QuoteVerification/QVL/Src/AttestationLibrary/src/QuoteVerification/QuoteConstants.h

Reverts intel/SGXDataCenterAttestationPrimitives#56
Need to sync with other SGX components.
Revert it now and will fix this issue later.

Revert "Fix incorrect key type constants"

---

driver/linux/encl.c
driver/linux/encl.h
driver/linux/reclaim.c

Drop the synchronize_srcu() from sgx_encl_mm_add() and replace it with a
mm_list generation concept to avoid deadlock when adding a mm during
dup_mmap()/fork(), and to ensure copied PTEs are zapped.
When dup_mmap() runs, it holds mmap_sem for write in both the old mm and
new mm.  Invoking synchronize_srcu() while holding mmap_sem of a mm that
is already attached to the enclave will deadlock if the reclaimer is in
the process of walking mm_list, as the reclaimer will try to acquire
mmap_sem (of the old mm) while holding encl->srcu for read.
INFO: task ksgxswapd:181 blocked for more than 120 seconds.
ksgxswapd       D    0   181      2 0x80004000
Call Trace:
__schedule+0x2db/0x700
schedule+0x44/0xb0
rwsem_down_read_slowpath+0x370/0x470
down_read+0x95/0xa0
sgx_reclaim_pages+0x1d2/0x7d0 …

x86/sgx: Fix deadlock and race conditions between fork() and EPC reclaim

---

QuoteGeneration/quote_wrapper/quote/qe_logic.cpp

One debug flag unused anymore caused debug build failure found by #89 .

Fix Debug build

---

driver/linux/main.c

The value defined by X86_FEATURE_SGX is populated in the kernel's CPU feature bitmask by querying CPUID. This properly checks for SGX support. X86_FEATURE_SGX1 defines as value which is defined in kernel source as X86_FEATURE_TPR_SHADOW which is not a good proxy for SGX1 support.

Check for SGX support with X86_FEATURE_SGX not X86_FEATURE_SGX1

---

driver/linux/driver.c

The INT0E0C device denotes SGX support in the DSDT ACPI table. Add this as an alias to the SGX driver. This allows the module to be auto-probed when the module is build with the kernel (rather than DKMS) and the entry is present in the machine's DSDT.
There were also a couple things I noticed when trying to build the module as part of the kernel build:
1. The headers in driver/linux/include are not included. I had to copy them to driver/linux
Note: I compiled the driver into the kernel by symlinking driver/linux into the linux source tree (at drivers/platform/x86/sgx) and then modifying the Makefile at drivers/platform/x86
2. The latest tip of master can only build against 5.7+. I'm not sure if distros are responsible for back-porting to older kernels?

Add module alias for ACPI device INT0E0C

---

driver/linux/ioctl.c

Shifting a signed integer value of 1 by 31 or more bits will cause
overflow and can lead to undefined behaviour. Fix this by adding
a UL suffix to ensure an unsigned long is being shifted.
Signed-off-by: Colin Ian King colin.king@canonical.com

Fix signed integer overflow on shift

---

driver/linux/ioctl.c

This pull request fix enclave size validation on sgx_validate_secs() method. The current implementation of sgx_validate_secs breaks if maximum enclave size is used.

Linux Driver: fix enclave size validation

---

driver/linux/Makefile
driver/linux/main.c

Different variant of distro kernels export different set of symbols.
Directly look for those needed in $(KDIR)/Module.symvers to avoid hardcoded kernel version

Linux Driver: look for exported symbols in Makefile

---

QuoteGeneration/installer/linux/rpm/libsgx-dcap-ql/build.sh

This commit resolves the following build failure:
pkgroot/libsgx-dcap-ql-dev/include/
pkgroot/libsgx-dcap-ql-dev/include/sgx_dcap_ql_wrapper.h
~/downloads/alinux2/linux-sgx/external/dcap_source/QuoteGeneration
~/downloads/alinux2/linux-sgx/external/dcap_source/QuoteGeneration/installer/linux/rpm/libsgx-dcap-ql/libsgx-dcap-ql-1.10.100.4 ~/downloads/alinux2/linux-sgx/external/dcap_source/QuoteGeneration
error: line 40: Unknown tag: Recommends:     libsgx-dcap-quote-verify >= 1.10.100.4-1.al7
make[1]: *** [Makefile:121: rpm_sgx_dcap_ql_pkg] Error 1
make[1]: Leaving directory '/root/downloads/alinux2/linux-sgx/external/dcap_source/QuoteGeneration'
make: *** [Makefile:265: rpm_libsgx_dcap_ql] Error 2
The fix refers to libsgx-dcap-quote-verify/build.sh.
Signed-off-by: Jia Zhang …

Fix rpm build failure for libsgx-dcap-ql

---

SampleCode/QuoteVerificationSample/App/App.cpp

In Linux, `strncpy` may overwrite the final `\0` if user input buffer is too long, which may cause potential buffer overflow. 
Signed-off-by: Hongyan Jiang <hongyan.jiang@intel.com>

Fix possible off-by-one issue in Quote verification sample

---

QuoteVerification/dcap_quoteverify/inc/sgx_urts_wrapper.h
QuoteVerification/dcap_quoteverify/linux/config.cpp
QuoteVerification/dcap_quoteverify/sgx_dcap_quoteverify.cpp

After introducing sgx_pthead, QVL needs additional OCALLs which define in uRTS library. 
The PR adds the additional OCALL wrappers in QVL library, then user's application doesn't need to link uRTS in non-SGX capable env.

Remove SGX uRTS dependency in quote verification library

---

QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.0/debian/control
QuoteGeneration/installer/linux/rpm/libsgx-dcap-ql/libsgx-dcap-ql.spec

libsgx-dcap-ql package doesn't depends on libsgx-ae-qve package.
Users have to install unnecessary and unwanted package due to this incorrect Depends/Requires.
Fixes [#linux-sgx/756](https://github.com/intel/linux-sgx/issues/756)

Update libsgx-dcap-ql installer package dependency

---

QuoteGeneration/installer/linux/common/libsgx-pce-logic/Makefile
QuoteGeneration/installer/linux/common/libsgx-qe3-logic/Makefile

Remove unused empty folder `/libsgx-pce-logic` and `/libsgx-pce-logic` in root folder after `libsgx-pce-logic` and `libsgx-qe3-logic` deb installers installed.
No such issue found on RPM based OS and this fix doesn't change RPM installer behavior.
fixes https://github.com/intel/linux-sgx/issues/762

Fix libsgx-pce-logic and libsgx-qe3-logic deb installer

---

QuoteGeneration/buildenv.mk
tools/SGXPlatformRegistration/Makefile
tools/SGXPlatformRegistration/buildenv.mk

In contrast to other coreutils binaries used throughout the code,
cp(1) gets called with an absolute path which assumes the binary
resides in `/bin`. This commit removes the absolute path to search
for cp(1) relative to the search paths given in the `PATH`
environment variable.
Using an absolute path to call binaries is incompatible with
distributions which do not follow the Filesystem Hierachy Standard;
NixOS is an example. Also, as other coreutils binaries merely mention
the binary's name, it is more consistent to call cp(1) in the same way.
Signed-off-by: Vincent Haupert <mail@vincent-haupert.de>

Call cp(1) relative to `PATH`

---

QuoteGeneration/buildenv.mk
QuoteGeneration/qcnl/linux/Makefile
QuoteGeneration/qpl/linux/Makefile
QuoteVerification/buildenv.mk
QuoteVerification/dcap_quoteverify/linux/Makefile
QuoteVerification/dcap_quoteverify/linux/config.cpp
QuoteVerification/dcap_quoteverify/sgx_dcap_pcs_com.cpp

The current repo only provides libsgx_dcap_quoteverify.so, a dynamic library, for quote verification. 
There lacks the corresponding static library which would be useful in many cases, like when integrating the function of quote verification into the browser via the Webassembly technique.
Regarding this, I add a new compiling option called "GEN_STATIC"  in makefile which enables developers to directly generate a series of static libraries.
The compiling command is `make GEN_STATIC=1`, the generated static libraries are: libsgx_dcap_quoteverify.a, libdcap_quoteprov.a, libsgx_default_qcnl_wrapper.a.
In addition, I slightly adjust the method of the library loading in libsgx_dcap_quoteverify.a so as to successfully work with libdcap_quoteprov.a. Also, since the quote provider library for tdx …

Enable generate static libraries of dcap_quoteverify

---

QuoteVerification/QvE/Enclave/qve.cpp

Doing the version check before checking `p_quote_collateral` for `NULL` can lead dereferencing a null pointer.
Signed-off-by: Thomas Niederberger <thomas@niederb.ch>

Reorder code to prevent dereferencing a potential null pointer

---

QuoteVerification/dcap_quoteverify/sgx-dcap-quoteverify-rs/Cargo.toml
QuoteVerification/dcap_quoteverify/sgx-dcap-quoteverify-rs/src/lib.rs
QuoteVerification/dcap_quoteverify/sgx-dcap-quoteverify-sys/Cargo.toml
QuoteVerification/dcap_quoteverify/sgx-dcap-quoteverify-sys/build.rs
QuoteVerification/dcap_quoteverify/sgx-dcap-quoteverify-sys/src/lib.rs
SampleCode/RustQuoteVerificationSample/Cargo.toml
SampleCode/RustQuoteVerificationSample/README.md
SampleCode/RustQuoteVerificationSample/src/main.rs

1. Use `Result` for returning errors
2. Add new API to get collateral
3. Add new `tee` APIs to get supplemental data size and verify quote
4. Upgrade Rust edition to 2021
5. Update sample code to use `tee` APIs instead of the old `sgx` APIs
6. Add `TD_ENV` feature to the sample code to support running on TDX environment
Signed-off-by: yao-ji <yao.ji@intel.com>

Update Rust QVL APIs

---

License.txt

Now they are licensed under the 3-clause BSD license. 
Also update AE name list to add new AEs.

Update license of Intel signed architecture enclaves

---

QuoteGeneration/pccs/migrations/03_db_version_3.js

I get a migration error while setting up a mysql database with the PCCS 
This fix makes it works.

:bug: fix a typo in db migration 3 script

---

QuoteGeneration/quote_wrapper/tdx-attest-sys/build.rs

- typo in `cargo:rerun-if-changed=` specification
- wrong clang args passed when SGX_SDK is not defined

tdx-attest-sys: fix build.rs

---

QuoteGeneration/quote_wrapper/tdx_attest/tdx_attest.c
QuoteGeneration/quote_wrapper/tdx_attest/tdx_attest.h

We do not support use NULL as report data when calling `tdx_att_get_report` and `tdx_att_get_quote`

Fix R3AAL eror code if report data is NULL

---

QuoteGeneration/Makefile

`exit` with a negative argument is not supported by `sh`, thus leading to the following output:
```
ERROR: Please decompress prebuilt enclave package before compiling.
Exiting......
/bin/sh: 1: exit: Illegal number: -2
```

QuoteGeneration/Makefile: Fix incorrect usage of exit

---

QuoteGeneration/quote_wrapper/quote/qe_logic.cpp

Change `SGX_QE_PLATFORM_LIB_UNAVAILABLE` to `SGX_QL_PLATFORM_LIB_UNAVAILABLE`
`SGX_QE_PLATFORM_LIB_UNAVAILABLE` doesn't seem to exist.

Fix typo in comments

---

QuoteVerification/QvE/AttestationLibrary/AttestationLibrary.vcxproj
QuoteVerification/QvE/AttestationParsers/AttestationParsers.vcxproj
QuoteVerification/QvE/AttestationParsers/AttestationParsers.vcxproj.filters
QuoteVerification/dcap_quoteverify/AttestationLibrary_untrusted/AttestationLibrary_untrusted.vcxproj
QuoteVerification/dcap_quoteverify/AttestationParsers_untrusted/AttestationParsers_untrusted.vcxproj
QuoteVerification/dcap_quoteverify/AttestationParsers_untrusted/AttestationParsers_untrusted.vcxproj.filters

Fix QVL/QvE build failure in Windows on TDX 1.5 branch.
- QVL/QvE need to add TDX related files in VS project.
- Ignore the warning which introduced in latest SDK C++ runtime.

Fix QVL/QvE build failure in Windows on TDX 1.5 branch

---

QuoteVerification/dcap_quoteverify/sgx-dcap-quoteverify-sys/Cargo.toml

With `0.60.1`:
```
thread 'main' panicked at '"_sgx_ql_qv_supplemental_t_union_(anonymous_at_/usr/include/sgx_qve_header_h_93_5)" is not a valid Ident', /home/harald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.64/src/fallback.rs:791:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

build(deps): increase bindgen version

---

QuoteVerification/dcap_quoteverify/sgx-dcap-quoteverify-sys/build.rs

If `SGX_SDK` is unset, a single `-I` argument is passed to the C compiler, which leads to an unsuccesful build, even if the needed header files are present in the standard include path.

fix(sgx-dcap-quoteverify-sys): successfull build with SGX_SDK unset

---

QuoteVerification/QuoteVerificationService/Dockerfile
QuoteVerification/QuoteVerificationService/src/package.json

QVS is  always building with latest version of node:lts-slim image.
Latest version of node image is affected by race conditions, and running cmake-js instantly after npm install fails with "Text file busy" error on docker containers.
https://github.com/nodejs/docker-node/issues/1918
As a workaround package script 'wait-for-cmake-js' has been added.
It tries every second (up to 10 seconds) to use simplest --version command on cmake-js to test if cmake-js became operable.

Added active waiting for cmake-js (Text file busy) race condiion

---

QuoteGeneration/README.md

After I built the Intel(R) SGX DCAP Quote Generation Library and the Intel(R) SGX Default Quote Provider Library installers, I couldn't find the generated installers located.
```bash
$ cd linux/installer/deb/
cd: no such file or directory: linux/installer/deb/
```
The reason is that the README description is wrong. The correct path should be `installer/linux/deb`.
```bash
$ cd installer/linux/deb
```

QuoteGeneration/README.md: Correct installers path descriptions.

---

QuoteGeneration/buildenv.mk

Check to see if the Intel SGX SDK is explicitly specified. If it is, include the appropriate environment file. Otherwise, display a warning message that the Intel SDK is missing.

Fix PCCS docker build failure caused by missing Intel SDK

---

.github/workflows/c-cpp.yml

Prebuilt Intel(R) SGX SDK Installer is required for building.

Add workflow file and CI action script for Ubuntu 22.04

---

QuoteGeneration/quote_wrapper/tdx-attest-rs/src/lib.rs

Use all zero report_data instead of null ptr to fix program panic of ` tdx_att_get_quote` and `tdx_att_get_report` when `Option<&tdx_report_data_t>` is None.
fixes #404

Update parameters in tdx-attest Rust wrapper

---

driver/linux/README.md

The Linux DCAP driver is deprecated and no longer maintained by Intel.

Add deprecation note.
